<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ELink.Indi\ELink.Indi.csproj" />
    <ProjectReference Include="..\ELink.Core\ELink.Core.csproj" />
    <ProjectReference Include="..\ELink.Contracts\ELink.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
